<a href="https://colab.research.google.com/github/metoberu/mexampage.0/blob/main/Calender1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import discord

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
import pandas as pd

In [3]:
SP_CREDENTIAL_FILE = '/content/calenderbot-359914-bef7f3a7f65c.json'
SP_COPE = [
          'https://spreadsheets.google.com/feeds',
          'https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive.file',
          'https://www.googleapis.com/auth/drive'
  
]
SP_SHEET_KEY = '1arFJ7kINskjhD8MJfUghj8gLnCme3oROck1LPJUjyxY'
SP_SHEET = '2022_8'

In [4]:
credentials =ServiceAccountCredentials.from_json_keyfile_name(SP_CREDENTIAL_FILE, SP_COPE)
gc = gspread.authorize(credentials)

In [5]:
#スプレッドシートの選択
sh = gc.open_by_key(SP_SHEET_KEY)
#”でじらぼ”参照では、shはssと表記

In [6]:
#シートの選択
worksheet = sh.worksheet(SP_SHEET)

In [7]:
#表示するための装置"data"
data = worksheet.get_all_values()
data

[['2022年8月', 'カレンダー', '', '', ''],
 ['日にち', '曜日', '予定１', '予定２', '日記'],
 ['１', '水', '', '', ''],
 ['2', '', '', '', ''],
 ['3', '', '', '', ''],
 ['4', '', '', '', ''],
 ['5', '土', '', '', ''],
 ['6', '日', '', '', ''],
 ['7', '', '', '', ''],
 ['8', '', '', '', ''],
 ['9', '', '', '', ''],
 ['10', '', '', '', ''],
 ['１１', '', '', '', ''],
 ['１２', '', '', '', ''],
 ['１３', '土', '中間発表', '', ''],
 ['１４', '日', '', '', ''],
 ['１５', '', '', '', ''],
 ['１６', '', '', '', ''],
 ['17', '', '', '', ''],
 ['１８', '', '', 'test', ''],
 ['１９', '', '', '', '(めとべる)弟の読書感想文手伝ったら、「もはや論文だからダメ」って却下された'],
 ['２０', '土', '中間発表', '', ''],
 ['２１', '日', '', '', ''],
 ['２２', '', '', 'test', ''],
 ['２３', '', '', '', ''],
 ['２４', '', '', '', ''],
 ['２５', '', '', '', ''],
 ['２６', '', '', '', ''],
 ['２７', '土', '', '', ''],
 ['２８', '日', '', '', ''],
 ['２９', '', '', '', ''],
 ['３０', '', '', '', ''],
 ['３１', '', '', '', '']]

In [8]:
#colabでの清書版カレンダー表示
df = pd.DataFrame(data[2:],columns=data[1])
df

   日にち 曜日   予定１   予定２                                      日記
0    １  水
1    2
2    3
3    4
4    5  土
5    6  日
6    7
7    8
8    9
9   10
10  １１
11  １２
12  １３  土  中間発表
13  １４  日
14  １５
15  １６
16  17
17  １８           test
18  １９                 (めとべる)弟の読書感想文手伝ったら、「もはや論文だからダメ」って却下された
19  ２０  土  中間発表
20  ２１  日
21  ２２           test
22  ２３
23  ２４
24  ２５
25  ２６
26  ２７  土
27  ２８  日
28  ２９
29  ３０
30  ３１

In [9]:
#セルに入力
st=sh.worksheet(SP_SHEET)
st.update_acell("C22","中間発表")
df

   日にち 曜日   予定１   予定２                                      日記
0    １  水
1    2
2    3
3    4
4    5  土
5    6  日
6    7
7    8
8    9
9   10
10  １１
11  １２
12  １３  土  中間発表
13  １４  日
14  １５
15  １６
16  17
17  １８           test
18  １９                 (めとべる)弟の読書感想文手伝ったら、「もはや論文だからダメ」って却下された
19  ２０  土  中間発表
20  ２１  日
21  ２２           test
22  ２３
23  ２４
24  ２５
25  ２６
26  ２７  土
27  ２８  日
28  ２９
29  ３０
30  ３１

In [10]:
#セルに入力
st=sh.worksheet(SP_SHEET)
st.update_acell("C22","中間発表")
df

   日にち 曜日   予定１   予定２                                      日記
0    １  水
1    2
2    3
3    4
4    5  土
5    6  日
6    7
7    8
8    9
9   10
10  １１
11  １２
12  １３  土  中間発表
13  １４  日
14  １５
15  １６
16  17
17  １８           test
18  １９                 (めとべる)弟の読書感想文手伝ったら、「もはや論文だからダメ」って却下された
19  ２０  土  中間発表
20  ２１  日
21  ２２           test
22  ２３
23  ２４
24  ２５
25  ２６
26  ２７  土
27  ２８  日
28  ２９
29  ３０
30  ３１

In [11]:
#今日のひにち表示
import datetime

kyou= datetime.date.today()
print(kyou)

2022-08-25

In [12]:
#年、月、日の表示
time = datetime.datetime.now()
print(time.year)
print(time.month)
print(time.day)

2022
8
25

In [13]:
#セルの内容を読みだして書き加える
st.update_cell(int(time.day)+2,4,"test")

{'spreadsheetId': '1arFJ7kINskjhD8MJfUghj8gLnCme3oROck1LPJUjyxY',
 'updatedRange': 'main!D27',
 'updatedRows': 1,
 'updatedColumns': 1,
 'updatedCells': 1}

In [14]:
#月の最初の曜日だけ入力

#月末の日を取得
import datetime
import calendar
Last_day= calendar.monthrange(time.year,time.month )[1]

#"曜日"リスト
youbi=["日","月","火","水","木","金","土"]

first_youbi=
num_youbi=youbi.index(first_youbi)

#曜日リスト
while num_youbi in range(0,Last_day):
  num_youbi +=1
  st.update_cell(int(),2,youbi[num_youbi])

else:
  break

SyntaxError: ignored